version: "3.1"
services:

    memcached:
      image: memcached:alpine
      container_name: user-api-memcached

    redis:
      image: redis:alpine
      container_name: user-api-redis

    mysql:
      image: mysql:5.7
      container_name: user-api-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=user_db
        - MYSQL_USER=admin
        - MYSQL_PASSWORD=admin
      ports:
        - "4306:3306"

    webserver:
      image: nginx:alpine
      container_name: user-api-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8081:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: user-api-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

